{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-core",
    "version": "0.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "latest.release"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-core-0.6.2.jar",
          "url": "minecraft-codev-core-0.6.2.jar",
          "size": 270312,
          "sha512": "ac35f1fe2eee8a5a4fbb0272746adda6e72e42e57679aee56c4adaa8e3b94baea907c411622dc060cf629194df6bf5529c0f2a5f57bdef4d21b6e383095a9466",
          "sha256": "f9cfd19dd91bc4ca423a9d9e4d3c4be8f6de0439b62c9f2fdec54a96af3e6e02",
          "sha1": "680e082fedaabedd8d2994befc8c8560102c14d0",
          "md5": "fecafbeea4a0e0659231b1598f2ed665"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "net.msrandom",
          "module": "side-annotations",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "latest.release"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-core-0.6.2.jar",
          "url": "minecraft-codev-core-0.6.2.jar",
          "size": 270312,
          "sha512": "ac35f1fe2eee8a5a4fbb0272746adda6e72e42e57679aee56c4adaa8e3b94baea907c411622dc060cf629194df6bf5529c0f2a5f57bdef4d21b6e383095a9466",
          "sha256": "f9cfd19dd91bc4ca423a9d9e4d3c4be8f6de0439b62c9f2fdec54a96af3e6e02",
          "sha1": "680e082fedaabedd8d2994befc8c8560102c14d0",
          "md5": "fecafbeea4a0e0659231b1598f2ed665"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-core-0.6.2-sources.jar",
          "url": "minecraft-codev-core-0.6.2-sources.jar",
          "size": 32561,
          "sha512": "0bffeae835436249f143c4740ca54c6a55b6cbce1b9871eed6aebb7556e245848687bd908fc5f4a34f9b43b5de03d9be73a3434fd4afd7981a5aa75212839ffd",
          "sha256": "1247b4d60c44ac3cc60bfcff1c408971a67df43913d02c234e3f52bd95464892",
          "sha1": "9e8cc5638ee4a8c1a27b7e93dfae3eecc0ce1e2d",
          "md5": "4bbea15e27c0d8e9a50e39e087233470"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-core-0.6.2-javadoc.jar",
          "url": "minecraft-codev-core-0.6.2-javadoc.jar",
          "size": 261,
          "sha512": "737247cd2103ece4a6c4d835b77549e47050814bf73dad71a30f0e9588c7ed5f79a6eccd5ce62f1b9aa096b7b2eaea2d6a7d1c93a6ae7a5bd3d7963559a77c40",
          "sha256": "f6ef558c26b3e24077e48bcde0d1ba08d9dbd60fe70655ba6239930adb6f7b6d",
          "sha1": "df14db827c94cabc582a82cc5548dc63d2de0a5e",
          "md5": "fc10e9dd5cbcdc2760083c54d7165d55"
        }
      ]
    }
  ]
}
