{
  "formatVersion": "1.1",
  "component": {
    "group": "net.msrandom",
    "module": "minecraft-codev-includes",
    "version": "0.6.5-dust",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "minecraft-codev-includes-0.6.5-dust.jar",
          "url": "minecraft-codev-includes-0.6.5-dust.jar",
          "size": 24718,
          "sha512": "cbaa260b9b46295f8f04268edd7f8b7a6a5ca6c75792f5be6efeb028a762f474068fc571aaea0d15be583fc9569c88f12f9d4428bf37e7e614f9c8b8327cc205",
          "sha256": "2ebf58f61bf518f63623184293c5d2223e9d729d8d8a7e33470a5cf15e6a6ec7",
          "sha1": "9fde4cefdbab50faee4b0a90f1ecdefd8b2254e0",
          "md5": "86365f07e5d69b2fb59091c4d60e9b71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.6.5"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-codev-includes-0.6.5-dust.jar",
          "url": "minecraft-codev-includes-0.6.5-dust.jar",
          "size": 24718,
          "sha512": "cbaa260b9b46295f8f04268edd7f8b7a6a5ca6c75792f5be6efeb028a762f474068fc571aaea0d15be583fc9569c88f12f9d4428bf37e7e614f9c8b8327cc205",
          "sha256": "2ebf58f61bf518f63623184293c5d2223e9d729d8d8a7e33470a5cf15e6a6ec7",
          "sha1": "9fde4cefdbab50faee4b0a90f1ecdefd8b2254e0",
          "md5": "86365f07e5d69b2fb59091c4d60e9b71"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-includes-0.6.5-dust-sources.jar",
          "url": "minecraft-codev-includes-0.6.5-dust-sources.jar",
          "size": 5583,
          "sha512": "0f87b2325ccc08115b9b488e0d4ddcc6958b41dcefb6fe5c53d4c80930f9f20202d4fab273961abfffc5c249d6b21b6a76f6d590b5c658115cc797cf99fe7ce7",
          "sha256": "a17486dbfea05ac74e0cd487e3013bb5e0a492d6ef7cc912a0b1de097113dd29",
          "sha1": "335cc91b1ce688facc759ca219d55c77fc92b9fc",
          "md5": "368d4d63c3867351431c6d773e68bf45"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-codev-includes-0.6.5-dust-javadoc.jar",
          "url": "minecraft-codev-includes-0.6.5-dust-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
