name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    - name: Checkout
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Test and Publish
      run: ./gradlew test publishAllPublicationsToProjectRepository

    - name: Deploy to maven-repo branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: maven-repo
        publish_dir: publish
        force_orphan: true