name: Publish

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Test and Publish
        run: ./gradlew test publish